lexik_jwt_authentication:
    secret_key:       '%env(resolve:JWT_SECRET_KEY)%'            # required for token creation
    public_key:       '%env(resolve:JWT_PUBLIC_KEY)%'            # required for token verification
    pass_phrase:      '%env(JWT_PASSPHRASE)%'                    # required for token creation
    user_identity_field: username
    token_ttl:        3600

gesdinet_jwt_refresh_token:
    single_use: true